version: '3.7'
services:

  db:
    image: mysql:5.7
    command:
      mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql:/docker-entrypoint-initdb.d"

  swagger-ui:
    build:
      context: .
      target: swagger-ui
    ports:
      - 3000:3000
    command:
      sh /usr/share/nginx/run.sh

  viron:
    build:
      context: .
      target: viron
    working_dir: /viron
    ports:
      - 8080:8080
    environment:
      - SHELL=/bin/bash
    command: npm run start

